[workspace]
authors = ["Claudius Kienle <claudius.kienle@tu-darmstadt.de>"]
channels = ["conda-forge"]
name = "Papers-Website"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
serve = { cmd = ["jekyll", "serve"]}
deploy = { cmd = ["jekyll", "build"]}

[dependencies]
ruby = ">=3.4.4,<4"
gcc = ">=15.1.0,<15.2"
make = ">=4.4.1,<5"
cxx-compiler = ">=1.0.0,<2"
